clear;
rx = comm.SDRuReceiver ('Platform','X310', ...
    'IPAddress','192.168.10.2', ...
    'CenterFrequency',2.5e9, ...
    'MasterClockRate',200e6, ...
    'DecimationFactor',256);

    for counter = 1:20
        data = rx();
    end

release(rx);
